package org.Tasks;
import java.io.IOException;
import java.io.OutputStream;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptException;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.Select;
import java.io.Closeable;
import javax.swing.Box.Filler;
public class ExecutableClass1 extends BaseClass1{
public static void main(String[] args) throws IOException,InterruptedException {
launchChromeBrowser();
launchUrl("https://adactinhotelapp.com/");
maxWindow();
WebElement txtUser=driver.findElement(By.id("username"));
fill(txtUser,excelRead(0,1));
WebElement txtPassword=driver.findElement(By.id("password"));
fill(txtPassword,excelRead(1,1));
WebElement btnLog=driver.findElement(By.id("login"));
btnLogin(btnLog);
Thread.sleep(3000);
WebElement locatingArea=driver.findElement(By.xpath("//select[@id='location']"));
Select s=new Select(locatingArea);
s.selectByIndex(1);
WebElement hotelSelection=driver.findElement(By.xpath("//select[@id='hotels']"));
Select s1 = new Select(hotelSelection);
s1.selectByIndex(1);
WebElement roomNo = driver.findElement(By.xpath("//select[@name='room_nos']"));
Select s2 = new Select(roomNo);
s2.selectByIndex(1);
WebElement roomSelection = driver.findElement(By.xpath("//select[@name='adult_room']"));
Select s3 = new Select(roomSelection);
s3.selectByIndex(1);
WebElement btnClick = driver.findElement(By.xpath("//input[@id='Submit']"));
btnLogin(btnClick);
WebElement radioClick = driver.findElement(By.xpath("//input[@name='radiobutton_1']"));
radioClick.click();
WebElement btnSubClick = driver.findElement(By.xpath("//input[@type='submit']"));
btnSubClick.click();
WebElement firstName = driver.findElement(By.xpath("//input[@name='first_name']"));
fill(firstName, excelRead(2, 1));
WebElement lastname = driver.findElement(By.xpath("//input[@name='last_name']"));
fill(lastname, excelRead(3, 1));
WebElement addres = driver.findElement(By.xpath("//textarea[@name='address']"));
fill(addres, excelRead(4, 1));
WebElement creditCard = driver.findElement(By.xpath("//input[@name='cc_num']"));
fill(creditCard, excelRead(5, 1));
WebElement typeOfCredit = driver.findElement(By.xpath("//select[@name='cc_type']"));
Select s4 = new Select(typeOfCredit);
s4.selectByIndex(1);
WebElement monthSelect = driver.findElement(By.xpath("//select[@name='cc_exp_month']"));
Select s5 = new Select(monthSelect);
s5.selectByIndex(2);
WebElement yearSelect = driver.findElement(By.xpath("//select[@name='cc_exp_year']"));
Select s6 = new Select(yearSelect);
s6.selectByIndex(2);
WebElement ccv = driver.findElement(By.xpath("//input[@name='cc_cvv']"));
fill(ccv, excelRead(6, 1));
WebElement btnBookClick = driver.findElement(By.xpath("//input[@name='book_now']"));
btnLogin(btnBookClick);
String read = excelRead(5, 1);
 System.out.println(read);
JavascriptExecutor js= (JavascriptExecutor)driver;
Thread.sleep(10000);
WebElement orderNUm = driver.findElement(By.xpath("(//input[@class='disable_text'])[15]"));
js.executeScript("arguments[0].ScrollIntoView(true)",orderNUm);
String attribute = orderNUm.getAttribute("value");
System.out.println(attribute);
System.out.println(attribute);
OutputStream fo = null;
book.write(fo);
System.out.println("Card Number:"+fo);
}
}
